# Generated by Django 3.2 on 2022-02-09 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tumbnail',
            new_name='thumbnail',
        ),
    ]
