# Generated by Django 3.2 on 2022-02-11 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='posts',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='posts',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='postview',
            old_name='posts',
            new_name='post',
        ),
    ]
